### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by ajhalls** [maxogden/voxel-builder#20]
Running on CentOS and I got this at the end of the npm install, which of course gave errors when I tried npm start.

```
ndarray@1.0.15 node_modules/ndarray
â””â”€â”€ iota-array@1.0.0

orthogami@1.1.0 node_modules/orthogami
â”œâ”€â”€ signum@1.0.0
â”œâ”€â”€ contour-2d@1.0.0
â”œâ”€â”€ boxpack@0.1.0
â”œâ”€â”€ interval-tree-1d@1.0.0 (binary-search-bounds@1.0.0)
â””â”€â”€ ndarray-ops@1.2.2 (cwise-compiler@1.0.0)

ndarray-stl@1.0.1 node_modules/ndarray-stl
â”œâ”€â”€ normals@0.1.0
â”œâ”€â”€ isosurface@0.1.0
â””â”€â”€ ao-mesher@0.2.10 (cwise-compiler@0.1.0, typedarray-pool@0.1.2, greedy-mesher@1.0.2)

voxel-critter@1.0.0 node_modules/voxel-critter
â”œâ”€â”€ voxel-mesh@0.2.1
â”œâ”€â”€ inherits@2.0.1
â”œâ”€â”€ voxel-creature@0.1.0 (inherits@1.0.0)
â”œâ”€â”€ get-pixels@1.1.0 (node-bitmap@0.0.1, through@2.3.4, omggif@1.0.5, ppm@0.0.0, ndarray-pack@1.1.1, jpeg-js@0.0.3, pngparse@1.1.4)
â”œâ”€â”€ voxel-engine@0.20.1 (voxel-view@0.0.6, inherits@1.0.0, pin-it@0.0.1, collide-3d-tilemap@0.0.1, spatial-trigger@0.0.0, aabb-3d@0.0.0, voxel-physical@0.0.10, voxel-control@0.0.7, tic@0.2.1, spatial-events@0.0.1, voxel-region-change@0.1.0, voxel-raycast@0.2.1, voxel-texture@0.5.6, kb-controls@0.0.2, gl-matrix@2.0.0, three@0.56.0, interact@0.0.2)
â””â”€â”€ voxel@0.3.1 (inherits@1.0.0)

voxel-2d-print@1.0.0 node_modules/voxel-2d-print
â”œâ”€â”€ contour-2d@1.0.0
â”œâ”€â”€ atlaspack@0.2.7
â”œâ”€â”€ color@0.4.4 (color-string@0.1.3, color-convert@0.2.1)
â”œâ”€â”€ save-pixels@1.0.0 (through@2.3.4, pngjs@0.4.0)
â”œâ”€â”€ ndarray-fill@0.1.0 (cwise@0.3.4)
â””â”€â”€ voxel-critter@0.1.2 (voxel-mesh@0.2.1, inherits@2.0.1, voxel-creature@0.1.0, voxel-engine@0.20.1, voxel@0.3.1)

ndarray-fill@1.0.1 node_modules/ndarray-fill
â””â”€â”€ cwise@1.0.4 (cwise-compiler@1.0.0, uglify-js@2.4.13, cwise-parser@1.0.0, static-module@1.0.0)

beefy@0.0.11 node_modules/beefy
â”œâ”€â”€ response-stream@0.0.0
â”œâ”€â”€ through@2.2.7
â”œâ”€â”€ colors@0.6.2
â”œâ”€â”€ filed@0.0.7
â”œâ”€â”€ optimist@0.3.7 (wordwrap@0.0.2)
â””â”€â”€ live-reload@0.2.0 (hound@1.0.4, watchr@2.1.6, shoe@0.0.5, reconnect@0.1.5, browserify-server@2.0.4)
[root@coursesaver cubecounting]# npm start

> voxel-painter@0.0.1 start /var/www/html/quizzes/cubecounting
> beefy demo.js:bundle.js 8080

listening on 8080
using browserify

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
  at errnoException (net.js:904:11)
  at Server._listen2 (net.js:1042:14)
  at listen (net.js:1064:10)
  at Server.listen (net.js:1138:5)
  at Object.<anonymous> (/var/www/html/quizzes/cubecounting/node_modules/beefy/index.js:118:4)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/var/www/html/quizzes/cubecounting/node_modules/beefy/bin/beefy:2:1)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:906:3

npm ERR! weird error 8
npm ERR! not ok code 0
```

**Comment by alexiiion** [comment]
Hi! Thank you for this great too!!

I had issues with getting it to run on Windows (tried Windows 8.1 and 10) and it turns out that increasing setting the beefy version to **"beefy": "2.1.5"** solved the problem. I thought I'd share in case other Windows users stumble installation issues. 

FYI detailed error info:
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn C:\Users\alex_hpi__workspace\voxel-builder-master\node_modules.bin\browserify ENOENT
  at exports._errnoException (util.js:746:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
  at child_process.js:1137:20
  at process._tickCallback (node.js:355:11)
